### ISSUE TITLE
log spam "unsupported tessellator flags"

### ISSUE THREAD

**Issue by Fiyorin** [makamys/Neodymium#15]
![image](https://user-images.githubusercontent.com/61357/226400396-db20d293-d8d4-4b7e-92da-c3addba5ff21.png)
getting this every second on GTNH, any ideas?

**Comment by Fiyorin** [comment]
nothing unusually at that world render position: chemically inert machine casing
another person reported the same issue

**Comment by chochem** [comment]
I have the same (also in GTNH). I narrowed it down a bit:

1) the position in the log does not seem to be correct. it only gives the right chunk.
2) the offending block seems to be enderio item conduits (well there might be more but that was it for me)

not sure if this is something to be fixed on the side of neodymium or enderio.

Specifically I am using:
EnderIO-2.4.2, from GTNH, https://github.com/GTNewHorizons/EnderIO
neodymium 0.1.8+nomixin (with unimixins-all-1.7.10-0.1.5)

**Comment by chochem** [comment]
nice, thanks!
