### ISSUE TITLE
How do I turn off Advanced OpenGL?

### ISSUE THREAD

**Issue by DarianLStephens** [makamys/Neodymium#18]
I haven't seen the option in my video settings for literal years at this point, so I thought it was just a permanent thing now, but Neodymium is prompting me to turn it off somehow.
Am I missing something? I've gone over each option here multiple times, and haven't seen it:
![2023-04-03_22 25 38](https://user-images.githubusercontent.com/15375876/229508658-a61382c6-9171-495e-81d3-11ce003e3601.png)

**Comment by couleurm** [comment]
don't you need optifine?

**Comment by DarianLStephens** [comment]
I know it was a vanilla thing a while ago, but I think Mojang removed the option.
I don't really want Optifine, because the 1.7.10 list says ArchaicFix + Neodymium theoretically has the better performance, and I want to use AF's occlusion culling and chunk updates.

**Comment by xdeadstokex** [comment]
![image](https://user-images.githubusercontent.com/129391255/229838441-6d1f89a6-65d3-41d1-9753-c94ceb35e53c.png)
in .minecraft folder 
click it
![image](https://user-images.githubusercontent.com/129391255/229839038-6c7b09ab-54f5-4d0a-95da-f2fc7c5f8a71.png)
turn this to false

**Comment by makamys** [comment]
Do you have ArchaicFix by any chance? It hides the Advanced OpenGL button (it doesn't disable the setting's effect, though.) Vanilla also hides it if you don't have an nvidia card. Another possible explanation is OptiFine forces it to appear, and you enabled it in the past while using OptiFine.

Either way, a simple way to solve this would be to make clicking Neodymium's chat message disable the setting.
