### ISSUE TITLE
Neodymium + Archaicfix Piston Chunk Glitches

### ISSUE THREAD

**Issue by Fabboz** [makamys/Neodymium#19]
When moving a block with a piston this happens.

pre:
![2023-04-13_07 01 32](https://user-images.githubusercontent.com/13696689/231658990-4209ccae-d489-4d49-81b3-9710e923a184.png)
level activated:
![2023-04-13_07 01 39](https://user-images.githubusercontent.com/13696689/231658995-3bd945ad-101b-478f-9a2a-9e7998c725c3.png)
placing a block:
![2023-04-13_07 01 45](https://user-images.githubusercontent.com/13696689/231658998-15bb2360-c5c0-4855-b772-022cf4b56fd1.png)
moving a glass block works normally:
![2023-04-13_07 01 57](https://user-images.githubusercontent.com/13696689/231659004-dafff44f-8c2d-426f-a69c-c257605ce384.png)

**Comment by quentin452** [comment]
try enabling enableThreadedChunkUpdates + enableOcclusionTweaks in archaicfix

**Comment by Fabboz** [comment]
ok this solves the problem completely.  unfortunately it is not compatible with optifine, I would need it because without my modpack it crashes because it can't load some 128x textures.  any advice for this too?

**Comment by makamys** [comment]
Can reproduce, turning off `enablePhosphor` also fixes it. (And for quentin's fix, only `enableOcclusionTweaks` is necessary.)

**Comment by Fabboz** [comment]
actually i can only reproduce this bug on an old nvidia graphic card with old driver.
i think the new driver solved the issue on an rtx2080 mobile.

**Comment by Fabboz** [comment]
the problem still occurs, the glitched chunk is the one where the character is located not where the piston is located

**Comment by xJon** [comment]
Is there any new workaround for this, avoiding the need to disable the Phosphor backport? Also I believe Occlusion Tweaks are no longer a part of ArchaicFix

**Comment by makamys** [comment]
The occlusion tweaks have been moved to FalseTweaks, I'm guessing their version still fixes it. (As a word of warning, FalseTweaks is prone to crashing in large packs with its default configs, but you can just disable all the modules other than the occlusion tweaks.)

**Comment by makamys** [comment]
I seem to have found the cause of this, you can try if [the last CI build](https://github.com/makamys/Neodymium/actions/runs/8346279733/artifacts/1339514062) fixes it for you.

**Comment by Fabboz** [comment]
The problem seems completely solved. Thank you
