### ISSUE TITLE
Crash Report 

### ISSUE THREAD

**Issue by 401090527** [makamys/Neodymium#2]
`---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 22-6-27 下午11:43
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at makamys.neodymium.renderer.NeoRenderer.getSaveDir(NeoRenderer.java:568)
	at makamys.neodymium.renderer.NeoRenderer.getRegionContaining(NeoRenderer.java:491)
	at makamys.neodymium.renderer.NeoRenderer.getNeoChunk(NeoRenderer.java:484)
	at makamys.neodymium.renderer.NeoRenderer.onWorldRendererChanged(NeoRenderer.java:457)
	at net.minecraft.client.renderer.WorldRenderer.handler$preSetDontDraw$zbf000(WorldRenderer.java:1180)
	at net.minecraft.client.renderer.WorldRenderer.func_78910_b(WorldRenderer.java)
	at net.minecraft.client.renderer.WorldRenderer.func_78913_a(WorldRenderer.java:156)
	at net.minecraft.client.renderer.RenderGlobal.func_72722_c(RenderGlobal.java:942)
	at net.minecraft.client.renderer.RenderGlobal.func_72719_a(RenderGlobal.java:1035)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1689)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1392)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3000)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at makamys.neodymium.renderer.NeoRenderer.getSaveDir(NeoRenderer.java:568)
	at makamys.neodymium.renderer.NeoRenderer.getRegionContaining(NeoRenderer.java:491)
	at makamys.neodymium.renderer.NeoRenderer.getNeoChunk(NeoRenderer.java:484)
	at makamys.neodymium.renderer.NeoRenderer.onWorldRendererChanged(NeoRenderer.java:457)
	at net.minecraft.client.renderer.WorldRenderer.handler$preSetDontDraw$zbf000(WorldRenderer.java:1180)
	at net.minecraft.client.renderer.WorldRenderer.func_78910_b(WorldRenderer.java)
	at net.minecraft.client.renderer.WorldRenderer.func_78913_a(WorldRenderer.java:156)
	at net.minecraft.client.renderer.RenderGlobal.func_72722_c(RenderGlobal.java:942)
	at net.minecraft.client.renderer.RenderGlobal.func_72719_a(RenderGlobal.java:1035)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1689)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1392)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [GCEntityClientPlayerMP['LSK'/890676, l='MpServer', x=8.50, y=66.62, z=8.50], MCH_ViewEntityDummy['McHeliDummyEntity'/6042, l='MpServer', x=0.00, y=-4.00, z=0.00]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-123,63,-51), Chunk: (at 5,3,13 in -8,-4; contains blocks -128,0,-64 to -113,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 2 total; [GCEntityClientPlayerMP['LSK'/890676, l='MpServer', x=8.50, y=66.62, z=8.50], MCH_ViewEntityDummy['McHeliDummyEntity'/6042, l='MpServer', x=0.00, y=-4.00, z=0.00]]
	Retry entities: 0 total; []
	Server brand: uranium,kcauldron,cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3020)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_321, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2365071992 bytes (2255 MB) / 3401580544 bytes (3244 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn128m -Xmx8192m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 74 mods loaded, 74 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAA	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	UCHIJAAAAAA	nametaghide{1.0.0} [NameTagHide] (minecraft.jar) 
	UCHIJAAAAAA	anothercommonbugfix{1.2.5} [Another Common Bug Fix] (minecraft.jar) 
	UCHIJAAAAAA	CodeChickenCore{1.1.4} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAAAA	NotEnoughItems{2.2.7-GTNH} [NotEnoughItems] (NotEnoughItems-1.7.10-2.2.7-GTNH.jar) 
	UCHIJAAAAAA	xaerominimap_core{1.7.10-1.0} [XaeroMinimapCore] (minecraft.jar) 
	UCHIJAAAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAAAA	FastCraft{1.25} [FastCraft] (AF.jar) 
	UCHIJAAAAAA	allmusic{2.5.11} [AllMusic] (AAMUS.jar) 
	UCHIJAAAAAA	damagemark{2.3} [DamageMark] (ADM.jar) 
	UCHIJAAAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAAAA	ArmorStatusHUD{1.28} [ArmorStatusHUD] (AHUD.jar) 
	UCHIJAAAAAA	MemoryCleaner{1.0} [Memory Cleaner] (AM.jar) 
	UCHIJAAAAAA	NEIAddons{1.12.14.40} [NEI Addons] (ANEIADON.jar) 
	UCHIJAAAAAA	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (ANEIADON.jar) 
	UCHIJAAAAAA	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (ANEIADON.jar) 
	UCHIJAAAAAA	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (ANEIADON.jar) 
	UCHIJAAAAAA	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (ANEIADON.jar) 
	UCHIJAAAAAA	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (ANEIADON.jar) 
	UCHIJAAAAAA	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (ANEIADON.jar) 
	UCHIJAAAAAA	falsepatternlib{0.9.1} [FalsePatternLib] (falsepatternlib-mc1.7.10-0.9.1.jar) 
	UCHIJAAAAAA	animfix{1.4.1} [AnimFix] (animfix-mc1.7.10-1.4.1.jar) 
	UCHIJAAAAAA	nshowmod{1.1} [NShowMod] (ANS.jar) 
	UCHIJAAAAAA	aiimprovements{0.0.1.19} [AI Improvements] (BAIImprovements-1.7.10-0.0.1b19-dev.jar) 
	UCHIJAAAAAA	CarpentersBlocks{3.3.8.2} [Carpenter's Blocks] (BCarpenter's Blocks v3.3.8.2 - MC 1.7.10.jar) 
	UCHIJAAAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (BCoFHCore-1.7.103.1.4-329.jar) 
	UCHIJAAAAAA	coretweaks{0.2.2} [CoreTweaks] (CoreTweaks-1.7.10-0.2.2.jar) 
	UCHIJAAAAAA	dsurround{1.0.6.4} [Dynamic Surroundings] (DynamicSurroundings-1.7.10-1.0.6.4.jar) 
	UCHIJAAAAAA	IC2{2.2.828-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.828a-experimental.jar) 
	UCHIJAAAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.504.jar) 
	UCHIJAAAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.504.jar) 
	UCHIJAAAAAA	ExtraPlanets{1.7.10-2.1.4} [Extra Planets] (ExtraPlanets-1.7.10-2.1.4.jar) 
	UCHIJAAAAAA	flansmod{1.54} [Flan's Mod Ultimate] (Flan's Mod Ultimate-1.54.jar) 
	UCHIJAAAAAA	mechapartspack{1.54} [Mecha Parts Pack] (Flan's Mod Ultimate-1.54.jar) 
	UCHIJAAAAAA	simplepartspack{1.54} [Simple Parts Pack] (Flan's Mod Ultimate-1.54.jar) 
	UCHIJAAAAAA	modernweaponspack{1.54} [Modern Weapons Pack] (Flan's Mod Ultimate-1.54.jar) 
	UCHIJAAAAAA	nerfpack{1.54} [Nerf Pack] (Flan's Mod Ultimate-1.54.jar) 
	UCHIJAAAAAA	titanpack{1.54} [Titan Pack] (Flan's Mod Ultimate-1.54.jar) 
	UCHIJAAAAAA	flansutilitypack{1.54} [Utility Pack] (Flan's Mod Ultimate-1.54.jar) 
	UCHIJAAAAAA	ww2pack{1.54} [WW2 Pack] (Flan's Mod Ultimate-1.54.jar) 
	UCHIJAAAAAA	yeoldpack{1.54} [Ye Olde Pack] (Flan's Mod Ultimate-1.54.jar) 
	UCHIJAAAAAA	zombiepack{1.54} [Zombie Pack] (Flan's Mod Ultimate-1.54.jar) 
	UCHIJAAAAAA	GalaxySpace{1.2.15 Pre-Final} [GalaxySpace] (GalaxySpace-1.7.10-1.2.15.jar) 
	UCHIJAAAAAA	ganysend{1.11.3} [Gany's End] (Ganys+End-1.11.3.jar) 
	UCHIJAAAAAA	ganysnether{1.8.3} [Gany's Nether] (Ganys+Nether-1.8.3.jar) 
	UCHIJAAAAAA	ganyssurface{1.12.8} [Gany's Surface] (Ganys+Surface-1.12.8.jar) 
	UCHIJAAAAAA	hbm{1.0.27 BETA (4277)} [Hbm's Nuclear Tech] (HBM-NTM-[1.0.27_X4277].jar) 
	UCHIJAAAAAA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (icp.jar) 
	UCHIJAAAAAA	inventorytweaks{1.5.14} [Inventory Tweaks] (inventorytweaks-1.7.10-1.5.14.jar) 
	UCHIJAAAAAA	matmos{1.7.10-35.4.3} [MAtmos] (matmos-1.7.10-35.4.3.jar) 
	UCHIJAAAAAA	mcheli{1.0.4} [MC Helicopter] (mcheli) 
	UCHIJAAAAAA	ForgeMultipart{1.2.0.347} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
	UCHIJAAAAAA	Mekanism{9.1.1} [Mekanism] (Mekanism.jar) 
	UCHIJAAAAAA	mixingasm{0.2.1} [Mixingasm] (mixingasm-1.7.10-0.2.1.jar) 
	UCHIJAAAAAA	MekanismGenerators{9.1.1} [MekanismGenerators] (mkf.jar) 
	UCHIJAAAAAA	neodymium{0.1.2} [Neodymium] (neodymium-1.7.10-0.1.2.jar) 
	UCHIJAAAAAA	netherlicious{3.2.2} [§6Netherlicious] (netherlicious-3.2.2.jar) 
	UCHIJAAAAAA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.7.10-1.1.0.jar) 
	UCHIJAAAAAA	nechar{1.0} [Not Enough Characters] (NotEnoughCharacters-1.7.10-1.0.jar) 
	UCHIJAAAAAA	customnpcs{1.7.10d} [CustomNpcs] (NPC.jar) 
	UCHIJAAAAAA	harvestcraft{1.0.6} [Pam's HarvestCraft] (Pam's-Harvestcraft-1.7.10Lb-1.0.6-GTNH.jar) 
	UCHIJAAAAAA	soundphysics{1.0.6} [Sound Physics] (Sound-Physics-1.7.10.jar) 
	UCHIJAAAAAA	spongemixins{1.2.0} [SpongeMixins Loader] (SpongeMixins-1.2.0 (1).jar) 
	UCHIJAAAAAA	Waila{1.5.19} [Waila] (Waila-1.7.10-1.5.19.jar) 
	UCHIJAAAAAA	WailaHarvestability{1.1.10-GTNH} [Waila Harvestability] (WailaHarvestability-1.7.10-1.1.10-GTNH.jar) 
	UCHIJAAAAAA	XaeroMinimap{21.10.26} [Xaero's Minimap] (Xaeros_Minimap_21.10.26_Forge_1.7.10.jar) 
	UCHIJAAAAAA	BambooMod{Minecraft@MC_VERSION@ var@VERSION@} [BambooMod] (竹8.5.jar) 
	UCHIJAAAAAA	ForgeMicroblock{1.2.0.347} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
	UCHIJAAAAAA	McMultipart{1.2.0.347} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 471.68' Renderer: 'NVIDIA GeForce GTX 980 Ti/PCIe/SSE2'
	CoFHCore: -[1.7.10]3.1.4-329
	Flan's Mod Content Packs: 
MCCOD-4 (filepath: C:\Users\rahe\Desktop\MCCOD-2022\.minecraft\Flan\MCCOD-4)
MCCOD-WF44 (filepath: C:\Users\rahe\Desktop\MCCOD-2022\.minecraft\Flan\MCCOD-WF44)
	Launched Version: LSK
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce GTX 980 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 471.68, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [音效包mat_zen-35-1.2.2.zip]
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 471.68
	OpenGlRenderer: NVIDIA GeForce GTX 980 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8`

**Comment by makamys** [comment]
Should be fixed in 0.1.3.
