### ISSUE TITLE
Strange glass colours

### ISSUE THREAD

**Issue by CorporalRaymond** [makamys/Neodymium#23]
Running the game with the neodymium and I just saw strange grass retextures on the sides
(https://github.com/makamys/Neodymium/assets/132620996/146ce65b-6edd-420c-b4bf-b43d69c99219)

Looks kind of strange would be nice if it looked better

**Comment by makamys** [comment]
What happened here? Did you find a solution?

I can't reproduce this by the way, grass looks the same for me (I verified this by enabling `enableVanillaChunkMeshes` and pressing F4+V to switch to the vanilla renderer on the fly.)
