### ISSUE TITLE
？？？

### ISSUE THREAD

**Issue by 323237216** [makamys/Neodymium#40]
How can I download it？

**Comment by makamys** [comment]
Click here:
![](https://github.com/makamys/Neodymium/assets/13667520/5b4aa57f-5f0c-4ce6-82bd-e884dd7f04bb)
Then one of these:
![](https://github.com/makamys/Neodymium/assets/13667520/4de98380-ed22-44e9-a686-2048233d5a7f)
`+nomixin` if you already have a mixin loader such as UniMixins. The second one if you need a standalone version.
