### ISSUE TITLE
Option to use Vulcan instead of OpenGL?

### ISSUE THREAD

**Issue by Raviexthegod** [makamys/Neodymium#46]
I prefer using the Vulcan Renderer over OpenGL as I tend to run into issues with the latter that the former doesn't have for me on other games and MC versions. The main reason for this is that OpenGL, while powerful, is an extremely bloated graphics library that can slow down even the most powerful computers.

PS: I tried adding the question label but couldn't find the dropdown.

**Comment by makamys** [comment]
This is out of scope for this project and probably a much greater undertaking than you think. The entirety of the vanilla rendering code and that of mods would need to be rewritten (and/or redirected to a translation layer with its own limitations). It's unfortunately not as simple as just redirecting all GL calls to Zink or something. It also doesn't help that I lack experience with Vulkan.

Labels on GitHub can only be added by maintainers or automation, I'll add one right now.

**Comment by couleurm** [comment]
https://modrinth.com/mod/vulkanmod

definitely not for 1.7.10 though
