### ISSUE TITLE
Blocks that render using triangles don't render properly

### ISSUE THREAD

**Issue by embeddedt** [makamys/Neodymium#5]
With Neodymium:

![2022-07-05_22 14 47](https://user-images.githubusercontent.com/42941056/177453302-0c772f68-4fcc-4aa8-9117-25253e61662b.png)

Without Neodymium:

![2022-07-05_22 14 49](https://user-images.githubusercontent.com/42941056/177453313-a3691b40-f68d-4038-a059-2d585d816135.png)

This is a modpack world, so getting it to you will be complicated, but I can try to strip it down if the images are not enough.

**Comment by embeddedt** [comment]
Turning "cull faces" off does not seem to fix the problem at runtime, even after F3+A.

**Comment by makamys** [comment]
Does it happen consistently when you visit the same spot? Does it stay if you move farther away? Are you saying F3+A doesn't fix it? And is there anything in the log that could indicate an error?

**Comment by embeddedt** [comment]
I'll confirm that it persists after a game restart today. It does persist even if you move farther away, you can see the missing faces at a distance. F3+A does not fix it, but using the hotkey to switch to the vanilla renderer does. I will also check the log.

**Comment by makamys** [comment]
If it persists, then it probably happens because Nd has trouble rendering a certain modded block. What blocks are there in those chunks that are rendered in a non-standard way? I can see this grey thing that might be a culprit.
![image](https://user-images.githubusercontent.com/13667520/177549696-0cbec2d8-be95-4e42-b299-19631543b770.png)
Try removing blocks in the chunk until the issue goes away, that should reveal which block was causing it.

**Comment by embeddedt** [comment]
You found it! The block in question is a Molecular Inscriber from Matter Overdrive. Placing it immediately causes the surrounding blocks to stop rendering, and breaking it fixes the issue.

![2022-07-06_08 48 40](https://user-images.githubusercontent.com/42941056/177553834-6f5afa0a-e8be-4f65-9e77-c0da15a55a8f.png)

I think it is supposed to have a base but that's the part that isn't rendering.

**Comment by makamys** [comment]
Looks like it uses the tessellator in triangle mode to render those blocks, while Nd is only compatible with quad rendering at the moment.
https://bitbucket.org/hrznstudio/mo-legacy-edition/src/460d23944be14a66b6bebe925f998c393a184719/src/main/java/matteroverdrive/client/render/block/RendererBlockInscriber.java#lines-72:82

To fix this, I will have to add logic to convert triangles into quads. I also plan to add an option to render everything using triangles in the future, that will also solve this.

**Comment by makamys** [comment]
Should be fixed now, but Matter Overdrive puts normal data in its vertices, which I'm ignoring. I won't close this issue until I'm confident this doesn't cause problems.

**Comment by makamys** [comment]
From the GL 2.1 spec I've gathered that normals are only used for lighting. It doesn't look like chunks are ever rendered with GL lighting enabled, so it should be fine. I've added a warning on the off-chance that it does happen.
