### ISSUE TITLE
Same problem https://github.com/makamys/CoreTweaks/issues/36

### ISSUE THREAD

**Issue by DDnerd001** [makamys/Neodymium#56]
but more shame...

[crash-2024-04-22_23.08.34-client.txt](https://github.com/makamys/Neodymium/files/15069017/crash-2024-04-22_23.08.34-client.txt)

**Comment by DDnerd001** [comment]
im an idiot

**Comment by Poopooracoocoo** [comment]
Why'd you close this issue?
