### ISSUE TITLE
Neodymium shakes the camera at high distances, similar to Bedrock

### ISSUE THREAD

**Issue by embeddedt** [makamys/Neodymium#6]
If this isn't trivial to fix without a significant performance drop, perhaps it should be ignored, but teleporting to somewhat far coordinates like X & Z -600,000 causes the camera to stutter and the block hitbox to not match the underlying block. I assume this is because the renderer is using floats internally that aren't relative to the player position.

**Comment by makamys** [comment]
> I assume this is because the renderer is using floats internally that aren't relative to the player position.

Yep, vertex positions are stored as absolute floats. This should be fixable by changing them to be relative to something like 1024x1024 chunk regions of the world. That should have no perceivable impact on performance, it would only increase the number of multidraw calls from 1 per render pass to 2-4 when you're near a region edge.

**Comment by Jokypond** [comment]
very annoying. wish it was fixed

**Comment by Richard-Rogalski** [comment]
https://cdn.discordapp.com/attachments/908158987730550805/1144690840917258290/IMG_7830.mov
Awesome demonstration of the bug, seems like it re implements bugs from the farlands era. 
to reproduce: `/tp 12550820 80 0`

I'm gonna try taking a crack at this one.
