### ISSUE TITLE
Crash with Latest FalsePatternLib + Triangulator

### ISSUE THREAD

**Issue by 0xKate** [makamys/Neodymium#7]
Hi, I was needing to update FalsePatternLib for other mods and found a crash on startup.

The pack used to load with Neodymium + Triangulator, but since the latest FalsePatternLib, I am getting this crash:

[fml-client-latest.log](https://github.com/makamys/Neodymium/files/9413137/fml-client-latest.log)

Loads:
falsepatternlib-mc1.7.10-0.9.4.jar
triangulator-mc1.7.10-1.7.3.jar
neodymium-1.7.10-0.1.5.jar

Crashes:
falsepatternlib-mc1.7.10-0.10.3.jar
triangulator-mc1.7.10-1.7.4.jar
neodymium-1.7.10-0.1.5.jar

Thanks for any assistance.

**Comment by makamys** [comment]
I believe Neodymium has nothing to do with this, it's the new Triangulator that's broken. I opened an issue about it here: https://github.com/FalsePattern/Triangulator/issues/27

**Comment by 0xKate** [comment]
Sorry about that, and thank you! Looks like everything is loading again with the new latest versions.

Works Now:
falsepatternlib-mc1.7.10-0.10.4.jar
triangulator-mc1.7.10-1.7.5.jar
neodymium-1.7.10-0.1.5.jar
SpongeMixins-1.5.0.jar
