### ISSUE TITLE
Crash with CoFHTweaks, Incompatibility with DragonAPI

### ISSUE THREAD

**Issue by iamsoNewBee** [makamys/Neodymium#9]
AS MY TITLE

**Comment by makamys** [comment]
I will see if it's something I can fix. In the meantime I can recommend [ArchaicFix](https://github.com/embeddedt/ArchaicFix) as an alternative that accomplishes similar things to CoFHTweaks and is fully compatible with Neodymium.

**Comment by iamsoNewBee** [comment]
> I will see if it's something I can fix. In the meantime I can recommend [ArchaicFix](https://github.com/embeddedt/ArchaicFix) as an alternative that accomplishes similar things to CoFHTweaks and is fully compatible with Neodymium.

I ADDED FPSPLUS ,BETTERFPS AND FOAMFIX AND STH ELSE IN MY MOD PACK BUT BLOCK TEXTURES IS MISSING.I WILL POST A PICTURE LATER AND I AM NOT SHUE IF IT HAVE TO DO WITH THOSE MODS.

**Comment by iamsoNewBee** [comment]
<img width="276" alt="image" src="https://user-images.githubusercontent.com/98573273/190849386-e6b51699-1a83-4ca2-bb45-3ba94a2cbe1c.png">
<img width="477" alt="image" src="https://user-images.githubusercontent.com/98573273/190849456-4e75ad34-482f-4a97-b707-265e4e277b0d.png">
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/98573273/190849474-6d365688-ef63-4f2c-a185-61b688f306d1.png">

**Comment by iamsoNewBee** [comment]
> <img alt="image" width="276" src="https://user-images.githubusercontent.com/98573273/190849386-e6b51699-1a83-4ca2-bb45-3ba94a2cbe1c.png">
> 
> <img alt="image" width="477" src="https://user-images.githubusercontent.com/98573273/190849456-4e75ad34-482f-4a97-b707-265e4e277b0d.png">
> 
> <img alt="image" width="1230" src="https://user-images.githubusercontent.com/98573273/190849474-6d365688-ef63-4f2c-a185-61b688f306d1.png">

WHEN I WAS MOVING ,THESE TESTURES CONTINUED TWINKLING.

**Comment by makamys** [comment]
Strange, I've never seen that before. Does it happen when running Neodymium alone? If not, try removing the other mods until you find the one that causes the issue.

**Comment by iamsoNewBee** [comment]
> Strange, I've never seen that before. Does it happen when running Neodymium alone? If not, try removing the other mods until you find the one that causes the issue.
IT IS PROBABLY CRASED BY mixingasm-1.7.10-0.2.2.

**Comment by iamsoNewBee** [comment]
> > Strange, I've never seen that before. Does it happen when running Neodymium alone? If not, try removing the other mods until you find the one that causes the issue.
> > IT IS PROBABLY CRASED BY mixingasm-1.7.10-0.2.2.

AS WELL AS gasstation-mc1.7.10-0.3.

**Comment by makamys** [comment]
I doubt those mods would be causing it, since they don't directly affect rendering in any way. Can you post your `fml-client-latest.log`?

**Comment by iamsoNewBee** [comment]
> I doubt those mods would be causing it, since they don't directly affect rendering in any way. Can you post your `fml-client-latest.log`?

SORRY I MADE A MISTAKE.IT`S PROBABLY CAUSED BY DRAGON API.

**Comment by makamys** [comment]
Oh, that seems more likely. It is known to affect rendering in strange ways, such as https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2879. It might help if you disable mipmapping.

**Comment by iamsoNewBee** [comment]
> Oh, that seems more likely. It is known to affect rendering in strange ways, such as [ReikaKalseki/Reika_Mods_Issues#2879](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2879). It might help if you disable mipmapping.

<img width="365" alt="image" src="https://user-images.githubusercontent.com/98573273/191010403-92d371b4-d328-4b8a-8718-f16484e4d30c.png">
NO WORK

**Comment by makamys** [comment]
Does the issue go away if you remove DragonAPI (and all mods that depend on it), but keep Neodymium?

**Comment by iamsoNewBee** [comment]
> Does the issue go away if you remove DragonAPI (and all mods that depend on it), but keep Neodymium?

PROBABLY YES

**Comment by makamys** [comment]
Hm, nope, I can't reproduce this. DragonAPI V31b + Neodymium 0.1.5 works fine (I had to disable the Forge splash, but that's an issue with DAPI itself).

**Comment by iamsoNewBee** [comment]
> 

???let me do some more tests

**Comment by iamsoNewBee** [comment]
> Hm, nope, I can't reproduce this. DragonAPI V31b + Neodymium 0.1.5 works fine (I had to disable the Forge splash, but that's an issue with DAPI itself).

<img width="466" alt="image" src="https://user-images.githubusercontent.com/98573273/191241765-1ad5370d-4466-4a58-8414-c9e9aa6924d8.png">
TRY TO REPRODUCE BY THIS MODS LIST.

**Comment by iamsoNewBee** [comment]
> > Hm, nope, I can't reproduce this. DragonAPI V31b + Neodymium 0.1.5 works fine (I had to disable the Forge splash, but that's an issue with DAPI itself).
> 
> <img alt="image" width="466" src="https://user-images.githubusercontent.com/98573273/191241765-1ad5370d-4466-4a58-8414-c9e9aa6924d8.png">
> 
> TRY TO REPRODUCE BY THIS MODS LIST.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/98573273/191249238-f0d6b867-8109-4e44-808a-cfd81e697d89.png">
more exactly

**Comment by makamys** [comment]
No issue with these (tested with the default configs). Can I see your log?
![](https://user-images.githubusercontent.com/13667520/191254767-5458802a-44d5-4fec-95d6-c1241dff3fe6.png)

**Comment by iamsoNewBee** [comment]
> No issue with these (tested with the default configs). Can I see your log? ![](https://user-images.githubusercontent.com/13667520/191254767-5458802a-44d5-4fec-95d6-c1241dff3fe6.png)

TRY TO ADD WITH DAPI?

**Comment by makamys** [comment]
Okay, I think I might know what's going on. If you have DragonAPI + GasStation + Neodymium, for some reason Neodymium fails to disable the vanilla world renderer, causing the world gets rendered twice. (Note how the water is more opaque than normal.) So it looks like you were right about GasStation being related, surprisingly.

![](https://user-images.githubusercontent.com/13667520/191328946-92a1e062-dd05-4f70-81a7-d91432764a61.png)

I want you to try something to confirm this: go to a place where you can see glitches, and press F4+V. This is a debug key shortcut that will disable Neodymium's renderer, revealing only whatever is left of the vanilla one. Take comparison screenshots with and without F4+V enabled, and post them here. For me, this is what happens when I press it.

![](https://user-images.githubusercontent.com/13667520/191328979-e61d749c-b6b8-4ffe-a2a7-32910c3e385a.png)

**Comment by makamys** [comment]
I found a quick fix. Add this line to your `config/mixingasm/transformer_inclusion_list.txt`:
```
Reika.DragonAPI.ASM.*
```

(Example:
![](https://user-images.githubusercontent.com/13667520/191332335-b09bda80-4f4b-41ca-a11e-c000e6348ad6.png) )


This fixes the issue for me.

**Comment by iamsoNewBee** [comment]
> I found a quick fix. Add this line to your `config/mixingasm/transformer_inclusion_list.txt`:
> 
> ```
> Reika.DragonAPI.ASM.*
> ```
> 
> (Example: ![](https://user-images.githubusercontent.com/13667520/191332335-b09bda80-4f4b-41ca-a11e-c000e6348ad6.png) )
> 
> This fixes the issue I described for me.

BY THE WAY ,BUGTORCH TAKES A PART,TOO.HOW TO DEAL WITH IT?(I DONT KNOW THE GRAMMER OFconfig/mixingasm/transformer_inclusion_list.txt:

**Comment by iamsoNewBee** [comment]
AS WELL AS CoreTweaks-1.7.10-0.2.6_1

**Comment by iamsoNewBee** [comment]
BUT THE ISSUE STILL EXTINCTS.I DONT KNOW WHICH MOD CAUSES IT ANYMORE.
[2022-09-21-7.log.gz](https://github.com/makamys/Neodymium/files/9612442/2022-09-21-7.log.gz)

**Comment by makamys** [comment]
> I DONT KNOW THE GRAMMER OF config/mixingasm/transformer_inclusion_list.txt

Here's mine, just replace yours with this one
[transformer_inclusion_list.txt](https://github.com/makamys/Neodymium/files/9616153/transformer_inclusion_list.txt)

**Comment by iamsoNewBee** [comment]
> > I DONT KNOW THE GRAMMER OF config/mixingasm/transformer_inclusion_list.txt
> 
> Here's mine, just replace yours with this one [transformer_inclusion_list.txt](https://github.com/makamys/Neodymium/files/9616153/transformer_inclusion_list.txt)

SORRY U MISUNDERSTOOD ME.THIS COULD ONLY TACKLE WITH DAPI`S ISSUE. BUT THERE ARE OTHER MODS CAUSEING THIS ISSUE LIKE WHAT I HAVE METHIONED ABROVE.

**Comment by makamys** [comment]
So you're saying the issue is still present when you remove DAPI?

**Comment by iamsoNewBee** [comment]
AFTER I HAVING DONE WHAT U TOLE ME TO DO,DAPI AND Neodymium WORK CORRECTLY.BUT : CoreTweaks and bugtorch MAY ALSO CAUSE THIS.

**Comment by makamys** [comment]
Hm... EnhancedVisuals or Triangulator, maybe?

**Comment by iamsoNewBee** [comment]
Triangulator is okay i will see Enh

**Comment by iamsoNewBee** [comment]
> AFTER I HAVING DONE WHAT U TOLE ME TO DO,DAPI AND Neodymium WORK CORRECTLY.BUT CoreTweaks and bugtorch MAY ALSO CAUSE THIS.(TESTED IN MY TESTING PACK) AND AFTER I REMOVING THEM IN MY WHOLE MODS PACK,I FOUND THAT THE ISSUE STILL PRESENTS LOL SO THERE MUST BE ANOTHER UNCERTAIN ONE

AND IF IT`S POSSIBLE THAT I COULD DO STH TO FIX THOSE IMCOMPAT LIKE WHAT I HAVE DONE TO DAPI?

**Comment by makamys** [comment]
I don't get any issue with CoreTweaks and BugTorch (I test with them normally). Using these:
![](https://user-images.githubusercontent.com/13667520/191504082-91537e17-ac05-462a-861b-cf23cbc978ac.png)

**Comment by iamsoNewBee** [comment]
> I don't get any issue with CoreTweaks and BugTorch (I test with them normally). Using these: ![](https://user-images.githubusercontent.com/13667520/191504082-91537e17-ac05-462a-861b-cf23cbc978ac.png)

MAYBE YOU SHOULD ADD THEM WITH DAPI (ALSO WITH GASSTATION?)

**Comment by makamys** [comment]
Oh. Yeah, the issue comes back if i add BugTorch or CoreTweaks next to GasStation+Neodymium+DAPI. Weird.

**Comment by makamys** [comment]
Okay, I think I managed to fix the issue on my side now. It was caused by a [totally useless hook](https://github.com/ReikaKalseki/DragonAPI/blob/12bf708bfe7444c6f55ffc37f1dab644ebedbb66/ASM/ASMCallsClient.java#L50-L52) in DAPI. Now this combo works fine:
![image](https://user-images.githubusercontent.com/13667520/191517584-9a317f59-b72e-42d4-9518-3142938aa70c.png)

You can download the new build here: https://nightly.link/makamys/Neodymium/suites/8398953316/artifacts/371170082

Also, I realized that the Mixingasm config workaround isn't reliable at all, you should remove that `Reika.DragonAPI.ASM.*` line I told you to add. (DragonAPI's transformer is re-entrant so Mixin excludes it after its first run either way.)

**Comment by iamsoNewBee** [comment]
THX. I WILL HAVE A TRY :D

**Comment by iamsoNewBee** [comment]
<img width="630" alt="image" src="https://user-images.githubusercontent.com/98573273/191522892-9b2b13f4-cda3-4072-8f83-057ed58a88d9.png">
EVERYTHING RETURNS TO NORMAL :D

**Comment by iamsoNewBee** [comment]
OH I ALMOST FORGET THIS... XD

**Comment by makamys** [comment]
Eh, it's fine, it's better to track the issues separately. (The new one is #11)
